
[General]
Version=1

[Preferences]
Username=
Password=2408
Database=
DateFormat=
CommitCount=0
CommitDelay=0
InitScript=

[Table]
Owner=
Name=GYM_CLASS_MEDICAL_CONSTRAINS
Count=364

[Record]
Name=MEDICAL_CONSTRAINS
Type=VARCHAR2
Size=50
Data=list(    "High blood pressure",
=    "Pregnancy",
=    "Heart disease",
=    "Severe asthma",
=    "Chronic obstructive pulmonary disease (COPD)",
=    "Epilepsy",
=    "Severe arthritis",
=    "Osteoporosis",
=    "Recent surgery",
=    "Severe back pain",
=    "Herniated disc",
=    "Severe joint pain",
=    "Tendonitis",
=    "Carpal tunnel syndrome",
=    "Severe migraine",
=    "Diabetes (uncontrolled)",
=    "Hyperthyroidism",
=    "Hypothyroidism",
=    "Severe anxiety",
=    "Severe depression",
=    "Obesity (morbid)",
=    "Severe anemia",
=    "Recent stroke",
=    "Angina",
=    "Congestive heart failure",
=    "Deep vein thrombosis",
=    "Pulmonary embolism",
=    "Severe varicose veins",
=    "Uncontrolled epilepsy",
=    "Hemophilia",
=    "Severe eczema",
=    "Psoriasis (severe)",
=    "Fibromyalgia (severe)",
=    "Lupus",
=    "Multiple sclerosis",
=    "Parkinson's disease",
=    "Alzheimer's disease",
=    "Dementia",
=    "Severe vertigo",
=    "Severe balance disorders",
=    "Scoliosis (severe)",
=    "Spinal stenosis",
=    "Rotator cuff injury",
=    "Severe plantar fasciitis",
=    "Severe muscle spasms",
=    "Hypermobile joints",
=    "Congenital heart defects",
=    "Severe chronic fatigue syndrome",
=    "Severe sleep apnea",
=    "Severe GERD",
=    "Severe IBS",
=    "Crohn's disease (flare-ups)",
=    "Ulcerative colitis (flare-ups)",
=    "Severe food allergies",
=    "Severe environmental allergies",
=    "Severe PTSD",
=    "Severe bipolar disorder",
=    "Severe schizophrenia",
=    "Autism spectrum disorder (with severe sensory issues)",
=    "Severe ADHD",
=    "Severe OCD",
=    "Severe personality disorders",
=    "Kidney failure",
=    "Liver disease",
=    "Severe gout",
=    "Severe psoriasis arthritis",
=    "Severe rheumatoid arthritis",
=    "Severe lupus nephritis",
=    "Severe Sjogren's syndrome",
=    "Severe Raynaud's disease",
=    "Marfan syndrome",
=    "Severe endometriosis",
=    "Polycystic ovary syndrome (PCOS) with severe symptoms",
=    "Severe chronic kidney disease",
=    "Severe hepatitis",
=    "Severe cirrhosis",
=    "Severe bronchitis",
=    "Severe sinusitis",
=    "Severe otitis media",
=    "Severe pancreatitis",
=    "Severe gallbladder disease",
=    "Severe hyperhidrosis",
=    "Severe hypoglycemia",
=    "Severe hyperglycemia",
=    "Severe metabolic syndrome",
=    "Severe polyneuropathy",
=    "Severe myopathy",
=    "Severe neuropathy",
=    "Severe vestibular disorders",
=    "Severe vision impairment",
=    "Severe hearing impairment",
=    "Severe cognitive impairment",
=    "Severe developmental disorders",
=    "Severe musculoskeletal disorders",
=    "Severe skin infections",
=    "Severe cellulitis",
=    "Severe lymphatic disorders",
=    "Severe immune disorders",
=    "Severe allergic reactions",
=    "Severe blood disorders")
Master=

[Record]
Name=CLASSID
Type=NUMBER
Size=
Data=list(select classId from GYM_CLASS)
Master=

